name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/wemogy/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PACKAGE_FEED_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        GitHub__Username: ${{ secrets.TEST_GITHUB_USERNAME }}
        GitHub__Token: ${{ secrets.TEST_GITHUB_TOKEN }}
      working-directory: src
    - name: Docker
      run: docker build .

    - name: Run the Action
      uses: './'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'release/1.0'
        projects: 'Single'
        prefix: ''
