name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - release/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    # Determine Release Version
    - uses: wemogy/next-version-action@2.0.2
      id: release-version
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projects: 'Single'
        prefix: ''

    # Create GitHub Release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.release-version.outputs.next-version }}
        name: Version ${{ steps.release-version.outputs.next-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
